- name: Get authorized_keys
  ansible.windows.win_get_url:
    url: https://github.com/kism.keys
    dest: "C:\\Users\\{{ service_account }}\\.ssh\\authorized_keys"

- name: Set execution policy
  ansible.windows.win_powershell:
    script: "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser"

- name: Run onboarding
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'files/Windows_10_Settings.ps1') }}"
  when: "'Windows 10' in ansible_facts['os_name']"

- name: Run onboarding
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'files/Windows_11_Settings.ps1') }}"
  when: "'Windows 11' in ansible_facts['os_name']"
